const marketDb = require('./market-db');
const marketSetup = require('./market-setup');
const marketThread = require('./market-thread');
const marketUi = require('./market-ui');
const marketNpcAi = require('./market-npc-ai');

module.exports = {
    initMarketTables: marketDb.initMarketTables,
    createListing: marketDb.createListing,
    lockItemsFromInventory: marketDb.lockItemsFromInventory,
    getListingsByCaravan: marketDb.getListingsByCaravan,
    getListingsBySession: marketDb.getListingsBySession,
    getSessionByThread: marketDb.getSessionByThread,
    getSessionByCaravan: marketDb.getSessionByCaravan,
    createMarketSession: marketDb.createMarketSession,
    buyItem: marketDb.buyItem,
    closeSession: marketDb.closeSession,
    returnUnsoldItems: marketDb.returnUnsoldItems,
    incrementNpcSpawn: marketDb.incrementNpcSpawn,
    getNpcSpawnCount: marketDb.getNpcSpawnCount,
    getActiveSessions: marketDb.getActiveSessions,
    getExpiredSessions: marketDb.getExpiredSessions,
    updateListingPrice: marketDb.updateListingPrice,
    getListingById: marketDb.getListingById,
    // staging
    stagingAddItem: marketDb.stagingAddItem,
    stagingRemoveItem: marketDb.stagingRemoveItem,
    getStagedItems: marketDb.getStagedItems,
    finalizeStagedItems: marketSetup.finalizeStagedItems,

    showMarketSetup: marketSetup.showMarketSetup,
    showStagingUI: marketSetup.showStagingUI,
    handleStageAddItemSelect: marketSetup.handleStageAddItemSelect,
    handleStagePriceModalSubmit: marketSetup.handleStagePriceModalSubmit,
    handleStageRemoveItemSelect: marketSetup.handleStageRemoveItemSelect,
    handleAddItemSelect: marketSetup.handleAddItemSelect,
    handlePriceModalSubmit: marketSetup.handlePriceModalSubmit,
    handleRemoveItemSelect: marketSetup.handleRemoveItemSelect,
    finalizeListings: marketSetup.finalizeListings,
    clearMarketListingsCache: marketSetup.clearMarketListingsCache,
    getMarketListingsCache: marketSetup.getMarketListingsCache,
    getItemInfo: marketSetup.getItemInfo,

    createMarketThread: marketThread.createMarketThread,
    closeMarketThread: marketThread.closeMarketThread,
    checkExpiredMarketSessions: marketThread.checkExpiredMarketSessions,
    setupMarketChecker: marketThread.setupMarketChecker,
    clearTimer: marketThread.clearTimer,
    activeTimers: marketThread.activeTimers,

    buildMarketImage: marketUi.buildMarketImage,
    buildMarketComponents: marketUi.buildMarketComponents,
    handleBuySelect: marketUi.handleBuySelect,
    handleBuyNow: marketUi.handleBuyNow,
    handleBuyQuantity: marketUi.handleBuyQuantity,
    handleBuyModalSubmit: marketUi.handleBuyModalSubmit,
    handleRefresh: marketUi.handleRefresh,
    handlePageNav: marketUi.handlePageNav,
    refreshMarketMessage: marketUi.refreshMarketMessage,
    handleOwnerPriceChange: marketUi.handleOwnerPriceChange,
    handlePriceChangeSelect: marketUi.handlePriceChangeSelect,
    handleNewPriceModalSubmit: marketUi.handleNewPriceModalSubmit,
    marketPages: marketUi.marketPages,

    spawnNpc: marketNpcAi.spawnNpc,
    scheduleNpcSpawn: marketNpcAi.scheduleNpcSpawn,
    handleNpcHaggle: marketNpcAi.handleNpcHaggle,
    handleNpcModalSubmit: marketNpcAi.handleNpcModalSubmit,
    parseNpcAction: marketNpcAi.parseNpcAction,
    NpcConversations: marketNpcAi.NpcConversations,
};
